<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Dashboard</title>
    <link rel="stylesheet" href="./public/style/globals.css">
</head>
<body>
    <h1>Dashboard</h1>
    <p>Welcome user <?= $user['name'] ?> </p>
    <hr>

    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Non dolore voluptates quod eaque id quo hic! Eum consequatur nemo at minus itaque eaque exercitationem amet, quam saepe error repellendus perspiciatis vel veritatis ullam veniam.</p>

    <button><a href="/logout.php">Logout</a></button>
    
</body>
</html>