<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Sessions-login</title>
    <link rel="stylesheet" href="./public/style/globals.css">
</head>
<body>
    <?php if(isset($message)): ?>
        <div class="message"> <?= $message ?> </div>
    <?php endif; ?>

    <h1>Login</h1>
    <form action="" method="post">
        <label>
            username
            <input type="text" name="username" placeholder="username">
        </label>
        <label>
            password
            <input type="text" name="password" placeholder="password">
        </label>

        <button type="submit">Login</button>
    </form>
    
</body>
</html>